[build]
base = "frontend"
command = "npm run build"
publish = "public"
environment = { NODE_ENV = "production", NODE_VERSION = "12" }

# Context specific settings - Overrides [build] settings

# -- Nothing here

# Branch specific settings - Overrides any context specific settings

[context.production.environment] # 'production' is a branch name
GATSBY_ACTIVE_ENV = "production"
SANITY_DATASET = "production"
[context.develop.environment] # 'develop' is a branch name
GATSBY_ACTIVE_ENV = "development"
SANITY_DATASET = "develop"
